apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-go-config
  namespace: k8s-go
  labels:
    app: k8s-go
    app.kubernetes.io/name: k8s-go
    app.kubernetes.io/version: "0.2"
    app.kubernetes.io/part-of: k8s-go-demo
    app.kubernetes.io/managed-by: kubectl
data:
  LOG_LEVEL: "info"
