apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-go

labels:
  - pairs:
      app.kubernetes.io/name: k8s-go
      app.kubernetes.io/version: "0.2"
      app.kubernetes.io/part-of: k8s-go-demo
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
    includeTemplates: true

images:
  - name: ghcr.io/yinebebt/k8s-go
    newTag: "0.2"

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pdb.yaml
