apiVersion: v1
kind: Secret
metadata:
  name: k8s-go-secrets
  namespace: k8s-go
  labels:
    app: k8s-go
    app.kubernetes.io/name: k8s-go
    app.kubernetes.io/version: "0.2"
    app.kubernetes.io/part-of: k8s-go
    app.kubernetes.io/managed-by: kubectl
type: Opaque
stringData:
  API_TOKEN: "replace-me"
