---
apiVersion: v1
kind: Service
metadata:
  name: k8s-go-service
  labels:
    app: k8s-go
spec:
  type: ClusterIP
  selector:
    app: k8s-go
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
