---
apiVersion: v1
kind: Service
metadata:
  name: k8s-go-service
  labels:
    app: k8s-go
spec:
  type: LoadBalancer
  selector:
    app: k8s-go
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-go-nodeport
  labels:
    app: k8s-go
spec:
  type: NodePort
  selector:
    app: k8s-go
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      nodePort: 30080
